name: image_picker_extended
description: A new Flutter package project.
version: 0.0.4
homepage: "http://repository.ecoinsoft.com:3000/kosal.sim/Image-Picker-Extended"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: any

dev_dependencies:
  flutter_test:
    sdk: flutter
